# SPDX-License-Identifier: Apache-2.0
# Commons Clause v1.0 applies — commercial use requires written permission. Contact: hello@bard0.com
# Copyright (c) 2026 Leonardo Capossio — bard0 design
#
#!/usr/bin/env python3
"""
Generate fixed Q95 tables for LITE_MODE Verilog implementation.

Outputs:
  1. Q95 reciprocal tables (recip_luma, recip_chroma) as Verilog initial blocks
  2. Q95 DQT values (zigzag order) for fixed JFIF header
  3. Complete 623-byte fixed JFIF header ROM as Verilog initial block

Usage:
  python gen_lite_tables.py
"""

import numpy as np
import sys
sys.path.insert(0, '.')
from jpeg_common import (
    STD_QUANT_TABLE_LUMA, STD_QUANT_TABLE_CHROMA,
    scale_quant_table, ZIGZAG_ORDER,
    DC_LUMA_BITS, DC_LUMA_VALS, AC_LUMA_BITS, AC_LUMA_VALS,
    DC_CHROMA_BITS, DC_CHROMA_VALS, AC_CHROMA_BITS, AC_CHROMA_VALS,
)

QUALITY = 95


def compute_q95_tables():
    """Compute Q95 scaled quantization tables and their reciprocals."""
    q_luma = scale_quant_table(STD_QUANT_TABLE_LUMA, QUALITY).flatten()
    q_chroma = scale_quant_table(STD_QUANT_TABLE_CHROMA, QUALITY).flatten()

    recip_luma = np.array([round(65536 / q) for q in q_luma], dtype=np.int32)
    recip_chroma = np.array([round(65536 / q) for q in q_chroma], dtype=np.int32)

    # Clamp reciprocals to 16-bit
    recip_luma = np.clip(recip_luma, 0, 65535)
    recip_chroma = np.clip(recip_chroma, 0, 65535)

    return q_luma, q_chroma, recip_luma, recip_chroma


def gen_verilog_reciprocal_init(q_luma, q_chroma, recip_luma, recip_chroma):
    """Generate Verilog initial block for Q95 reciprocal tables."""
    lines = []
    lines.append("// Q95 quantization tables and reciprocals (auto-generated by gen_lite_tables.py)")
    lines.append("// quality=95, scale=10")
    lines.append("")
    lines.append("// --- Q95 scaled luma table (raster order) ---")
    for i in range(64):
        lines.append(f"        qtable_luma[{i:2d}] = 8'd{q_luma[i]}; "
                     f"recip_luma[{i:2d}] = 16'd{recip_luma[i]};")

    lines.append("")
    lines.append("// --- Q95 scaled chroma table (raster order) ---")
    for i in range(64):
        lines.append(f"        qtable_chroma[{i:2d}] = 8'd{q_chroma[i]}; "
                     f"recip_chroma[{i:2d}] = 16'd{recip_chroma[i]};")

    return "\n".join(lines)


def build_fixed_jfif_header(q_luma, q_chroma, img_width=1280, img_height=720):
    """Build the complete fixed JFIF header as a byte array."""
    header = bytearray()

    # SOI
    header += bytes([0xFF, 0xD8])

    # APP0 (JFIF)
    header += bytes([0xFF, 0xE0, 0x00, 0x10,
                     0x4A, 0x46, 0x49, 0x46, 0x00,  # "JFIF\0"
                     0x01, 0x01,  # Version 1.1
                     0x00,        # Aspect ratio units
                     0x00, 0x01,  # X density
                     0x00, 0x01,  # Y density
                     0x00, 0x00]) # No thumbnail

    # DQT Luminance (table 0)
    header += bytes([0xFF, 0xDB, 0x00, 0x43, 0x00])
    # Q values in zigzag order
    for zi in range(64):
        raster_idx = ZIGZAG_ORDER[zi]
        header.append(int(q_luma[raster_idx]))

    # DQT Chrominance (table 1)
    header += bytes([0xFF, 0xDB, 0x00, 0x43, 0x01])
    for zi in range(64):
        raster_idx = ZIGZAG_ORDER[zi]
        header.append(int(q_chroma[raster_idx]))

    # SOF0
    header += bytes([0xFF, 0xC0, 0x00, 0x11, 0x08,
                     (img_height >> 8) & 0xFF, img_height & 0xFF,
                     (img_width >> 8) & 0xFF, img_width & 0xFF,
                     0x03,           # 3 components
                     0x01, 0x21, 0x00,  # Y: ID=1, H=2,V=1, quant=0
                     0x02, 0x11, 0x01,  # Cb: ID=2, H=1,V=1, quant=1
                     0x03, 0x11, 0x01]) # Cr: ID=3, H=1,V=1, quant=1

    # DHT tables (4 tables)
    for bits, vals, class_id, table_id in [
        (DC_LUMA_BITS, DC_LUMA_VALS, 0, 0),
        (AC_LUMA_BITS, AC_LUMA_VALS, 1, 0),
        (DC_CHROMA_BITS, DC_CHROMA_VALS, 0, 1),
        (AC_CHROMA_BITS, AC_CHROMA_VALS, 1, 1),
    ]:
        length = 2 + 1 + 16 + len(vals)  # length field + class/id + BITS + VALS
        header += bytes([0xFF, 0xC4,
                         (length >> 8) & 0xFF, length & 0xFF,
                         (class_id << 4) | table_id])
        header += bytes(bits)
        header += bytes(vals)

    # SOS
    header += bytes([0xFF, 0xDA, 0x00, 0x0C, 0x03,
                     0x01, 0x00,  # Y: DC=0, AC=0
                     0x02, 0x11,  # Cb: DC=1, AC=1
                     0x03, 0x11,  # Cr: DC=1, AC=1
                     0x00, 0x3F, 0x00])

    return header


def gen_verilog_header_rom(header_bytes):
    """Generate Verilog initial block for the fixed JFIF header ROM."""
    lines = []
    lines.append(f"// Fixed JFIF header ROM ({len(header_bytes)} bytes)")
    lines.append(f"// Auto-generated by gen_lite_tables.py (Q95, parameterized dimensions)")
    lines.append(f"localparam HEADER_SIZE = {len(header_bytes)};")
    lines.append(f"reg [7:0] header_rom [0:HEADER_SIZE-1];")
    lines.append(f"initial begin")
    for i, b in enumerate(header_bytes):
        lines.append(f"    header_rom[{i:3d}] = 8'h{b:02X};")
    lines.append(f"end")
    return "\n".join(lines)


def main():
    q_luma, q_chroma, recip_luma, recip_chroma = compute_q95_tables()

    print("=" * 70)
    print(f"LITE_MODE Q95 Tables (quality={QUALITY}, scale=10)")
    print("=" * 70)

    print("\n--- Reciprocal tables for quantizer.v ---\n")
    print(gen_verilog_reciprocal_init(q_luma, q_chroma, recip_luma, recip_chroma))

    header = build_fixed_jfif_header(q_luma, q_chroma)
    print(f"\n--- Fixed JFIF header ROM for jfif_writer.v ({len(header)} bytes) ---\n")
    print(gen_verilog_header_rom(header))

    # Verify header size
    # SOI(2) + APP0(18) + DQT_L(69) + DQT_C(69) + SOF0(19) + DHT(?) + SOS(14)
    print(f"\nHeader size: {len(header)} bytes")
    assert len(header) == 623, f"Expected 623 bytes, got {len(header)}"
    print("Header size verified: 623 bytes")

    # Print Q95 luma table (raster order) for verification
    print("\nQ95 Luma (raster): ", q_luma.tolist())
    print("Q95 Chroma (raster):", q_chroma.tolist())


if __name__ == "__main__":
    main()
